### ISSUE TITLE
获取WebQA数据

### ISSUE THREAD

**Issue by JancisWang** [INotWant/QA#1]
你好，我想要WebQA的原始数据，但是没有看到您的邮箱，请问您的邮箱是多少呢？非常感谢！

**Comment by INotWant** [comment]
等我把WebQA上传到百度云盘，然后发给你下载链接

**Comment by INotWant** [comment]
> 你好，我想要WebQA的原始数据，但是没有看到您的邮箱，请问您的邮箱是多少呢？非常感谢！

等我把WebQA上传到百度云盘，然后发给你下载链接

**Comment by INotWant** [comment]
> 你好，我想要WebQA的原始数据，但是没有看到您的邮箱，请问您的邮箱是多少呢？非常感谢！

https://pan.baidu.com/s/1z1uhtv0hHFhZUhyJ6-tWUA

**Comment by JancisWang** [comment]
> > 你好，我想要WebQA的原始数据，但是没有看到您的邮箱，请问您的邮箱是多少呢？非常感谢！
> 
> https://pan.baidu.com/s/1z1uhtv0hHFhZUhyJ6-tWUA

非常感谢！
